# Generated by Django 3.2.5 on 2021-12-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartubapp', '0002_auto_20211228_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
